### Your Turn

In the previous video, you saw an example of working with some MNIST digits data.  A link to the dataset can be found here: http://yann.lecun.com/exdb/mnist/.

First, let's import the necessary libraries.  Notice, there are also some imports from a file called `helper_functions`, which contains the functions used in the previous video.

In [15]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from helper_functions import show_images, show_images_by_digit, fit_random_forest_classifier2 
from helper_functions import fit_random_forest_classifier, do_pca, plot_components
import test_code as t

import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

`1.` Use pandas to read in the dataset, which can be found at the following address **'./data/train.csv'**.  If you have missing values, fill them with 0.  Take a look at info about the data using `head`, `tail`, `describe`, `info`, etc.  You can learn more about the data values from the article here: https://homepages.inf.ed.ac.uk/rbf/HIPR2/value.htm.

In [16]:
train = pd.read_csv('./data/train.csv')

train.fillna(0, inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6304 entries, 0 to 6303
Columns: 785 entries, label to pixel783
dtypes: float64(114), int64(671)
memory usage: 37.8 MB


`2.` Create a vector called **y** that holds the **label** column of the dataset.  Store all other columns holding the pixel data of your images in **X**.

In [17]:
y = train['label']
X = train.drop(['label'], axis = 1)

In [18]:
#Check Your Solution 
t.question_two_check(y, X)

That looks right!


`3.` Now use the `show_images_by_digit` function from the `helper_functions` module to take a look some of the `1`'s, `2`'s, `3`'s, or any other value you are interested in looking at.  Do they all look like what you would expect?

In [19]:
show_images_by_digit(9) # Try looking at a few other digits

/Users/ruihuang/Documents/Udacity/IntroML/DSND_Term1/lessons/Unsupervised/4_PCA/helper_functions.py:63: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  mat_data = X.iloc[indices[0][digit_num]].as_matrix().reshape(28,28)  #reshape images


`4.` Now that you have had a chance to look through some of the data, you can try some different algorithms to see what works well to use the X matrix to predict the response well.  If you would like to use the function I used in the video regarding random forests, you can run the code below, but you might also try any of the supervised techniques you learned in the previous course to see what works best.

If you decide to put together your own classifier, remember the 4 steps to this process:

**I.** Instantiate your model. (with all the hyperparameter values you care about)

**II.** Fit your model. (to the training data)

**III.** Predict using your fitted model.  (on the test data)

**IV.** Score your model. (comparing the predictions to the actual values on the test data)

You can also try a grid search to see if you can improve on your initial predictions.

In [20]:
# Remove the tag to fit the RF model from the video, you can also try fitting your own!
fit_random_forest_classifier(X, y)

[[201   0   1   0   0   1   6   0   0   0]
 [  0 234   3   0   0   1   1   2   2   0]
 [  1   4 214   1   2   0   1   5   0   0]
 [  1   0   5 176   0   3   1   1   0   4]
 [  1   0   0   0 171   0   2   0   0   4]
 [  2   1   0   4   1 172   2   0   4   0]
 [  3   0   0   0   1   2 205   0   0   0]
 [  0   0   7   0   6   0   0 206   2   4]
 [  0   1   1   7   3   3   0   0 185   2]
 [  1   1   1   3  11   0   0   3   3 185]]
0.9365689572321


0.9365689572321

`5.` Now the purpose of this lesson, to look at PCA.  In the video, I created a model just using two features.  Replicate the process below. You can use the same `do_pca` function that was created in the previous video.  Store your variables in **pca** and **X_pca**.

In [34]:
pca, X_pca = do_pca(30, X)

`6.` The **X_pca** has moved the original more than 700 features down to only 2 features that capture the majority of the variability in the pixel values.  Use the space below to fit a model using these two features to predict the written value.  You can use the random forest model by running `fit_random_forest_classifier` the same way as in the video. How well does it perform?

In [35]:
fit_random_forest_classifier(X_pca, y)

[[195   0   2   0   1   0   8   1   1   1]
 [  0 232   2   1   0   0   2   0   5   1]
 [  2   2 208   4   2   0   3   3   3   1]
 [  0   0   9 168   0   4   1   2   6   1]
 [  0   0   6   0 154   1   3   0   0  14]
 [  1   0   3   7   2 164   2   0   5   2]
 [  5   0   1   0   2   1 202   0   0   0]
 [  1   0   7   2   6   0   0 200   0   9]
 [  2   1   1  12   1   5   0   0 179   1]
 [  1   0   1   4  12   0   0  15   1 174]]
0.9014896684286401


0.9014896684286401

`7.` Now you can look at the separation of the values using the `plot_components` function.  If you plot all of the points (more than 40,000), you will likely not be able to see much of what is happening.  I recommend plotting just a subset of the data.  Which value(s) have some separation that are being predicted better than others based on these two components?

In [25]:
# Try plotting some of the numbers below - you can change the number
# of digits that are plotted, but it is probably best not to plot the 
# entire dataset.  Your visual will not be readable.

plot_components(X_pca[:50], y[:50])

`8.` See if you can find a reduced number of features that provides better separation to make predictions.  Say you want to get separation that allows for accuracy of more than 90%, how many principal components are needed to obtain this level of accuracy?  Were you able to substantially reduce the number of features needed in your final model?

In [36]:
for comp in range(2, 100):
    pca, X_pca = do_pca(comp, X)
    acc = fit_random_forest_classifier(X_pca, y)
    if acc > .90:
        print("With only {} components, a random forest acheived an accuracy of {}.".format(comp, acc))
        break

[[112   0  40  12   7   7  22   1   7   1]
 [  0 209   0   4   1   7   3   5   8   6]
 [ 37   2  75  29  15  22  35   0   9   4]
 [ 11   2  30  18  20  30  27  13  25  15]
 [  6   4  16  17  53  17  16   9  12  28]
 [  9   8  28  25  16  23  32   4  31  10]
 [ 30   4  50  21  10  24  38   3  30   1]
 [  3   4   3   8  36  10   3  91   8  59]
 [  6   6  27  32  18  30  25   7  42   9]
 [  2  12   3  18  30   9   4  58   7  65]]
0.34887073522345025
[[154   0   7   4   1  11  23   1   8   0]
 [  0 224   1   3   2   4   7   0   2   0]
 [ 17   3 121  34   5   2  37   0   8   1]
 [  3   3  55  60   5  15  28   4  15   3]
 [  7   0   2   4 102  12   1  12  12  26]
 [  9   0  12  12  26  57  27   6  29   8]
 [ 17   7  14  13   2  10 136   1  11   0]
 [  0   2   1   4  25   6   1 117  10  59]
 [ 15   2   9  24  28  38  36   0  50   0]
 [  2   2   2   2  44   3   1  55  13  84]]
0.5309947140797694
[[175   1  10   0   4  10   4   0   5   0]
 [  0 225   1   1   0   5   3   2   6   0]
 [ 14   1 162

[[194   0   3   1   0   2   6   2   1   0]
 [  0 234   2   1   0   0   2   0   3   1]
 [  1   2 212   3   2   0   2   3   3   0]
 [  0   0   7 166   0   6   1   2   6   3]
 [  0   0   3   0 155   1   4   1   1  13]
 [  1   0   2   8   1 164   0   0   5   5]
 [  5   0   1   0   2   2 200   0   1   0]
 [  1   0   6   1   5   0   2 196   2  12]
 [  1   2   0  11   2   8   0   0 176   2]
 [  2   0   2   3  14   1   0  14   1 171]]
0.8976453628063431
[[190   0   3   0   0   3  10   1   1   1]
 [  0 234   2   0   0   1   2   0   4   0]
 [  1   2 208   6   1   0   2   4   3   1]
 [  0   0   9 164   0   6   1   2   7   2]
 [  0   0   4   0 154   1   3   1   0  15]
 [  2   0   4   7   1 163   1   0   5   3]
 [  3   0   2   0   3   1 201   0   1   0]
 [  0   1   7   1   4   0   1 198   1  12]
 [  2   1   1  10   2   8   0   0 176   2]
 [  1   0   2   2  18   0   0  14   2 169]]
0.8923594425756848
[[195   0   3   1   0   1   7   1   1   0]
 [  0 234   1   0   1   0   2   0   4   1]
 [  3   2 206 

`9.` It is possible that extra features in the dataset even lead to overfitting or the [curse of dimensionality](https://stats.stackexchange.com/questions/65379/machine-learning-curse-of-dimensionality-explained).  Do you have evidence of this happening for this dataset?  Can you support your evidence with a visual or table?  To avoid printing out all of the metric results, I created another function called `fit_random_forest_classifier2`.  I ran through a significant number of components to create the visual for the solution, but I strongly recommend you look in the range below 100 principal components!

In [37]:
accs = []
comps = []
for comp in range(2, 100):
   comps.append(comp)
   pca, X_pca = do_pca(comp, X)
   acc = fit_random_forest_classifier2(X_pca, y)
   accs.append(acc)

In [38]:
plt.plot(comps, accs, 'bo');
plt.xlabel('Number of Components');
plt.ylabel('Accuracy');
plt.title('Number of Components by Accuracy');

In [39]:
np.max(accs), comps[np.where(accs == np.max(accs))[0][0]]

(0.9106198942815954, 51)